# modify the response schemas in almost paths because they are not completed. 
# add the dot at the end of each sentences

swagger: "2.0"


info: 
  title: "3pi APIs"
  description: |
    These are the RESTful APIs that can be used by users to send commands to the 3pi robot, in order to both obtain information from its sensors and to control it.
  version: "1.0.0"
  

host: 1.1.3.127 # Here i have to paste the real IP address


schemes: 
  - http
  - https


produces:
  - application/json
 
  
paths:


  /obtainstatus:
    get:
      description: Used to obtain the robot status.
      summary: |
        The user can send 
        a request to obtain the robot status
        (i.e. battery level).
      responses:
        200:
          description: |
            The response from the robot, it contains
            robot information.
          schema: # this is just an example, should be soon updated
            title: "Response"
            type: object
            proprierties:
              current_IP:
                type: string
              battery_level:
                type: string
        500:
          description: |
            For some reasons, it was impossible to 
            contact the robot.
          schema:
            title: "Error Message Status"
            type: object
            proprierties:
                error message:
                  type: string

        default:
          description: Unexpected error
          schema:
            title: "Error"
            type: object
            proprierties:
              error message:
                type: string

  
  
  /obtainmesurement:
    get:
      description: |
        This request is used to obtain enviromental mesurements in a specific place.
      summary: |
        Using  this API, it is possibile to send the place where the robot has to perform the mesurements and how long it has to wait if it faces some obstacles.
      parameters:
        - name: path
          description: This is the path that the robot has to follow, it is an integer (possible values are 1 or 2).
          type: integer
          minimum: 1
          maximum: 2
          exclusiveMaximum: false
          exclusiveMinimum: false
          in: query
          required: true
        - name: timeout
          description: How many seconds it has to wait if it faces obstacles, it is an integer (possibile values are from 1 to 5 seconds).
          type: integer
          minimum: 1
          maximum: 5
          exclusiveMaximum: false
          exclusiveMinimum: false
          in: query
          required: true
      responses:
        200:
          description: The response from the robot, it
            is an ACK.
          schema:
            title: Response
            type: object
            proprierties:
              response ACK:
                type: string
        500:
          description: An error occour an it was impossible to send the command.
          schema:
            title: Response Error
            type: object
            proprierties:
              error message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            title: "Error"
            type: object
            proprierties:
              error message:
                type: string

            
  
  /abort:
    get:
      description: Used to abort a specific task.
      summary: It is used to abort a specific tastk. When the robot recieves this command, it returns to the closest rest point.
      responses:
        200:
          description: It is an ACK.
          schema:
            title: Abort Response
            type: object
            proprierties:
              response message:
                type: string
        500:
          description: An error occour an it was impossibile to send the command.
          schema:
            title: Error Response Abort
            type: object
            proprierties:
              error message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            title: "Error"
            type: object
            proprierties:
              error message:
                type: string


  /update:
    get:
      description: Used when the user is waiting for updates from the robot.
      summary: It is used when the user is wondering about updates from the robot.
      responses:
        200:
          description: |
            The robot response, the fields  related to the mesurements could be set to  NULL if the task has not been completed.
          schema:
            title: Update Response
            type: object
            proprierties:
              current state:
                type: string
              temperature:
                type: string
        500:
          description: An error occour an it was impossibile to send the command.
          schema:
            title: Error Update Response
            type: object
            proprierties:
              error message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            titile: "Error"
            type: object
            proprierties:
              error message:
                type: string
  
 
  /visualcontrolmode:
    get: 
      description: In this API, the user just tells to the robot to switch to the visual control mode.
      summary:  The user can directly control the robot, sending it specific commands as query.
      responses:
        200:
          description: The robot sends back an ACK.
          schema: 
            title: ACK mode
            type: object
            proprierties:
              response message:
                type: string
        500:
          description: An error occour an it was impossibile to send the command.
          schema:
            title: Error Control Mode
            type: object
            proprierties:
              error message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            titile: "Error"
            type: object
            proprierties:
              error message:
                type: string
            
      

  /changedirection:
    get:
      description: Change the robot direction.
      summary: The user is able to specify the direction setting parameters in the query.
      parameters:
        - name: direction
          description: The robot direction (left = 1, right = 2, stop = 3, inversion = 4, forward = 5).
          minimum : 1
          maximum : 5
          exclusiveMinimum: false
          exclusiveMaximum: false
          type: integer
          in: query
          required: true
      responses:
        200:
          description: It is an ACK.
          schema: 
            title: Direction ACK
            type: object
            proprierties:
              direction response:
                type: string
        500:
          description: An error occour an it was impossibile to send the command.
          schema:
            title: Error Control Mode
            type: object
            proprierties:
              error message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            titile: "Error"
            type: object
            proprierties:
              error message:
                type: string
   
          
  /changespeed:  
    get:
      description: Change the robot speed.
      summary: The user is able to increase or decrease the robot speed in the visual control mode. The available speed are 1 , 2 ,3, 4.
        Type 0 to stop the robot.
      parameters:
        - name: speed
          description: The robot speed
          minimum : 0 
          maximum : 4
          exclusiveMinimum: false
          exclusiveMaximum: false
          type: integer
          in: query
          required: true
      responses:
        200:
          description: It is an ACK.
          schema:
            title: Speed ACK
            type: object
            properties:
              resonse message:
                type: string
        500:
          description: An error occours and it was impossible to send the command.
          schema:
            title: Error Speed ACK
            type: object
            properties:
              resonse message:
                type: string
        default:
          description: Unexpected Error.
          schema:
            titile: "Error"
            type: object
            properties:
              error message:
                type: string
                
            
      
          
          
    
        
      

